"""empty message

Revision ID: 19068067a365
Revises: 74be00424d1
Create Date: 2015-05-17 21:41:18.650633

"""

# revision identifiers, used by Alembic.
revision = '19068067a365'
down_revision = '74be00424d1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pwdhash',
               existing_type=mysql.VARCHAR(collation=u'latin1_general_ci', length=100),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pwdhash',
               existing_type=mysql.VARCHAR(collation=u'latin1_general_ci', length=100),
               nullable=False)
    ### end Alembic commands ###
